Repository League-of-Foundry-Developers/foundry-vtt-types, pull requests merged in 2021-02, with the labels that each got.

#237 Move SearchFilter stub to other UI classes
  index.d.ts
  types/ui/searchFilter.d.ts
Labels: enhancement, foundry 0.7.9

#247 Remove issue assignee and replace type check action
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/wrong_type.md
  .github/workflows/checks.yml
Labels: bug, enhancement

#255 Fix Entity.prepareData
  types/framework/entities/actor.d.ts
  types/framework/entities/item.d.ts
  types/framework/entity.d.ts
Labels: bug, foundry 0.7.9

#253 Fix type definition of duplicate
  .eslintrc.js
  test-d/utils.test-d.ts
  tsconfig.eslint.json
  tsconfig.json
  types/typesUtils.d.ts
  types/utils.d.ts
Labels: bug, foundry 0.7.9

#254 Improve type definitions of ActiveEffect
  test-d/framework/entities/activeEffect.test-d.ts
  types/framework/entities/activeEffect.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/embeddedEntity.d.ts
  types/framework/entities/item.d.ts
Labels: bug, foundry 0.7.9

#258 Fixup for ChatMessage
  test-d/framework/entities/chatMessage.test-d.ts
  types/framework/entities/chatMessage.d.ts
Labels: bug, foundry 0.7.9

#252 Couple the constructor params of already updated classes
  types/game.d.ts
  types/pixi/placeableObjects/placeableObject.d.ts
Labels: enhancement, foundry 0.7.9

#238 Update and move Dialog and add DialogButton
  index.d.ts
  test-d/applications/dialog.test-d.ts
  types/applications/application.d.ts
  types/applications/dialog.d.ts
  types/ui/dialog.d.ts
Labels: foundry 0.7.9, version update

#259 Add UserTargets class
  index.d.ts
  types/framework/entities/user.d.ts
  types/framework/userTargets.d.ts
Labels: foundry 0.7.9, version update

#261 Make it possible to dynamically add properties to a Game
  types/game.d.ts
Labels: bug, foundry 0.7.9

#262 Fix adding custom properties to Game
  test-d/game.test-d.ts
  types/game.d.ts
Labels: bug, foundry 0.7.9

#263 Create ConstructorOf<T> utility type
  types/core/config.d.ts
  types/core/settings/clientSettings.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/item.d.ts
  types/framework/entity.d.ts
  types/typesUtils.d.ts
  types/utils.d.ts
Labels: enhancement

#251 Add Draggable and associated tests
  index.d.ts
  test-d/ui/draggable.test-d.ts
  types/ui/draggable.d.ts
Labels: foundry 0.7.9, version update

#268 Add FEATURES constant and make ui a const
  index.d.ts
  types/constants.d.ts
  types/features.d.ts
  types/game.d.ts
Labels: foundry 0.7.9, version update

#265 Update CONFIG to 0.7.9
  types/core/config.d.ts
  types/pixi/pointSource.d.ts
Labels: foundry 0.7.9, version update

#269 Small Dialog Fixes
  types/applications/dialog.d.ts
Labels: bug, foundry 0.7.9

#243 Update PlaceableObject
  index.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/combat.d.ts
  types/framework/entities/scene.d.ts
  types/pixi/doorControl.d.ts
  types/pixi/measuredTemplate.d.ts
  types/pixi/placeableObjects/ambientLight.d.ts
  types/pixi/placeableObjects/ambientSound.d.ts
  types/pixi/placeableObjects/drawing.d.ts
  types/pixi/placeableObjects/measuredTemplate.d.ts
  types/pixi/placeableObjects/note.d.ts
  types/pixi/placeableObjects/placeableObject.d.ts
  types/pixi/placeableObjects/tile.d.ts
  types/pixi/placeableObjects/token.d.ts
  types/pixi/placeableObjects/wall.d.ts
  types/pixi/preciseText.d.ts
Labels: foundry 0.7.9, version update

#271 Update TextEditor and update to ES2020
  tsconfig.json
  types/core/textEditor.d.ts
Labels: foundry 0.7.9, version update

#270 Add first draft of DragDrop
  .eslintrc.js
  test-d/tsconfig.json
  test-d/types/applications/dialog.test-d.ts
  test-d/types/framework/entities/activeEffect.test-d.ts
  test-d/types/framework/entities/chatMessage.test-d.ts
  test-d/types/game.test-d.ts
  test-d/types/typesUtils.test-d.ts
  test-d/types/ui/draggable.test-d.ts
  test-d/types/utils.test-d.ts
  tsconfig.json
  types/ui/dragDrop.d.ts
Labels: foundry 0.7.9, version update

#273 Update some sheets to 0.7.9
  index.d.ts
  test-d/types/applications/forms/actorSheet.test-d.ts
  test-d/types/applications/forms/itemSheet.test-d.ts
  types/applications/application.d.ts
  types/applications/baseEntitySheet.d.ts
  types/applications/formApplication.d.ts
  types/applications/forms/actor.d.ts
  types/applications/forms/actorSheet.d.ts
  types/applications/forms/forms.d.ts
  types/applications/forms/itemSheet.d.ts
  types/applications/forms/setupConfigurationForm.d.ts
  types/applications/forms/userManagement.d.ts
  types/applications/journal/noteConfig.d.ts
  types/applications/placeables/placeablesConfig.d.ts
  types/applications/sidebar/applications/clientSettings.d.ts
  types/framework/entities/actor.d.ts
Labels: foundry 0.7.9, version update

#276 Add all shader classes for 0.7.9
  index.d.ts
  test-d/types/pixi/shaders/abstractBaseShader.test-d.ts
  types/core/config.d.ts
  types/pixi/pointSource.d.ts
  types/pixi/shaders/abstractBaseShader.d.ts
  types/pixi/shaders/blackHoleIlluminationShader.d.ts
  types/pixi/shaders/chromaColorationShader.d.ts
  types/pixi/shaders/emanationColorationShader.d.ts
  types/pixi/shaders/energyFieldColorationShader.d.ts
  types/pixi/shaders/fogColorationShader.d.ts
  types/pixi/shaders/ghostLightColorationShader.d.ts
  types/pixi/shaders/ghostLightIlluminationShader.d.ts
  types/pixi/shaders/hexaDomeColorationShader.d.ts
  types/pixi/shaders/lightDomeColorationShader.d.ts
  types/pixi/shaders/pulseColorationShader.d.ts
  types/pixi/shaders/pulseIlluminationShader.d.ts
  types/pixi/shaders/roilingIlluminationShader.d.ts
  types/pixi/shaders/standardColorationShader.d.ts
  types/pixi/shaders/standardIlluminationShader.d.ts
  types/pixi/shaders/sunburstColorationShader.d.ts
  types/pixi/shaders/sunburstIlluminationShader.d.ts
  types/pixi/shaders/torchColorationShader.d.ts
  types/pixi/shaders/torchIlluminationShader.d.ts
  types/pixi/shaders/waveColorationShader.d.ts
  types/pixi/shaders/waveIlluminationShader.d.ts
Labels: foundry 0.7.9, version update

#277 Make MODIFIERS extendable for all dice terms
  test-d/types/core/rolls/diceTerms/coin.test-d.ts
  test-d/types/core/rolls/diceTerms/die.test-d.ts
  test-d/types/core/rolls/diceTerms/fateDie.test-d.ts
  types/core/rolls/diceTerms/coin.d.ts
  types/core/rolls/diceTerms/diceTerm.d.ts
  types/core/rolls/diceTerms/die.d.ts
Labels: bug, foundry 0.7.9

#279 Update FormApplication to be less opinionated about getData return type.
  test-d/types/applications/forms/actorSheet.test-d.ts
  test-d/types/applications/forms/itemSheet.test-d.ts
  types/applications/baseEntitySheet.d.ts
  types/applications/formApplication.d.ts
  types/applications/forms/actorSheet.d.ts
  types/applications/forms/itemSheet.d.ts
  types/core/settings/clientSettings.d.ts
  types/framework/entity.d.ts
Labels: bug, foundry 0.7.9

#282 Add ActiveEffectConfig
  types/framework/entities/activeEffect.d.ts
  types/ui/activeEffectConfig.d.ts
Labels: foundry 0.7.9, version update

#284 Update Notifications to 0.7.9
  types/applications/application.d.ts
  types/ui/notifications.d.ts
Labels: foundry 0.7.9, version update

#286 Update Tabs to 0.7.9
  types/applications/application.d.ts
  types/ui/tabs.d.ts
Labels: foundry 0.7.9, version update

#287 Update dependencies and simplify some augments
  index.d.ts
  package-lock.json
  package.json
  types/augments/PIXI.d.ts
  types/augments/handlebars.d.ts
  types/augments/howler.d.ts
  types/augments/tinyMCE.d.ts
  types/core/config.d.ts
Labels: enhancement, foundry 0.7.9

#290 Improve typing of Entity
  test-d/types/framework/entity.test-d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/chatMessage.d.ts
  types/framework/entities/item.d.ts
  types/framework/entities/scene.d.ts
  types/framework/entity.d.ts
  types/typesUtils.d.ts
Labels: enhancement, foundry 0.7.9

#288 Allow update methods to accept dotted keys.
  test-d/types/framework/entities/chatMessage.test-d.ts
  test-d/types/framework/entity.test-d.ts
  test-d/types/typesUtils.test-d.ts
  test-d/types/utils.test-d.ts
  types/framework/entities/activeEffect.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/chatMessage.d.ts
  types/framework/entities/combat.d.ts
  types/framework/entities/item.d.ts
  types/framework/entities/scene.d.ts
  types/framework/entity.d.ts
  types/pixi/placeableObjects/placeableObject.d.ts
  types/typesUtils.d.ts
Labels: bug, foundry 0.7.9

#293 Update FilePicker to 0.7.9
  index.d.ts
  types/applications/application.d.ts
  types/applications/filePicker.d.ts
  types/ui/dragDrop.d.ts
  types/ui/filePicker.d.ts
Labels: foundry 0.7.9, version update

#294 Update SearchFilter to 0.7.9
  types/applications/application.d.ts
  types/applications/filePicker.d.ts
  types/ui/searchFilter.d.ts
Labels: foundry 0.7.9, version update

#296 Update FormDataExtended to 0.7.9
  types/applications/formApplication.d.ts
  types/applications/formDataExtended.d.ts
Labels: foundry 0.7.9, version update

#300 Add ActorTokenHelpers
  index.d.ts
  types/actorTokenHelpers.d.ts
Labels: foundry 0.7.9, version update

#301 Update Compendium to 0.7.9
  types/framework/compendium.d.ts
Labels: foundry 0.7.9, version update

#291 Update AV related classes to 0.7.9
  index.d.ts
  types/applications/application.d.ts
  types/core/config.d.ts
  types/core/hooks.d.ts
  types/core/webRtc/avClient.d.ts
  types/core/webRtc/avConfig.d.ts
  types/core/webRtc/avMaster.d.ts
  types/core/webRtc/avSettings.d.ts
  types/core/webRtc/easyRTCClient.d.ts
  types/typesUtils.d.ts
Labels: foundry 0.7.9, version update

#298 0.7.9/sidebar
  index.d.ts
  types/applications/application.d.ts
  types/applications/filePicker.d.ts
  types/applications/forms/settingsConfig.d.ts
  types/applications/sidebar.d.ts
  types/applications/sidebar/applications/actorDirectory.d.ts
  types/applications/sidebar/applications/chatLog.d.ts
  types/applications/sidebar/applications/combatTracker.d.ts
  types/applications/sidebar/applications/compendiumDirectory.d.ts
  types/applications/sidebar/applications/itemDirectory.d.ts
  types/applications/sidebar/applications/journalDirectory.d.ts
  types/applications/sidebar/applications/macroDirectory.d.ts
  types/applications/sidebar/applications/playlistDirectory.d.ts
  types/applications/sidebar/applications/rollTableDirectory.d.ts
  types/applications/sidebar/applications/sceneDirectory.d.ts
  types/applications/sidebar/applications/settings.d.ts
  types/applications/sidebar/sidebar.d.ts
  types/applications/sidebar/sidebarDirectory.d.ts
  types/applications/sidebar/sidebarTab.d.ts
  types/applications/sidebarTab.d.ts
  types/applications/sidebarTabs/chatLog.d.ts
  types/applications/sidebarTabs/combatTracker.d.ts
  types/applications/sidebarTabs/compendiumDirectory.d.ts
  types/applications/sidebarTabs/settings.d.ts
  types/applications/sidebarTabs/sidebarDirectories/actorDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/itemDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/journalDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/macroDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/playlistDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/rollTableDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectories/sceneDirectory.d.ts
  types/applications/sidebarTabs/sidebarDirectory.d.ts
  types/framework/entities/playlist.d.ts
  types/pixi/placeableObjects/token.d.ts
  types/ui/contextMenu.d.ts
  types/ui/draggable.d.ts
Labels: foundry 0.7.9, version update

#306 Make some small improvements to Roll
  foundry/roll.d.ts
Labels: enhancement, foundry 0.7.9, version update

#311 Remove enums
  foundry/application.d.ts
  foundry/applications/filePicker.d.ts
  foundry/applications/formApplications/baseEntitySheet.d.ts
  foundry/applications/sidebarTabs/chatLog.d.ts
  foundry/applications/sidebarTabs/sidebarDirectories/playlistDirectory.d.ts
  foundry/config.d.ts
  foundry/constants.d.ts
  foundry/entities/playlist.d.ts
  foundry/entities/scene.d.ts
  foundry/game.d.ts
  foundry/pointSource.d.ts
  foundry/roll.d.ts
  foundry/socketInterface.d.ts
  types/utils.d.ts
Labels: bug, foundry 0.7.9

#312 Add classes related to special effects (weather effects)
  foundry/config.d.ts
  foundry/specialEffect.d.ts
  foundry/specialEffects/autumnLeavesWeatherEffect.d.ts
  foundry/specialEffects/rainWeatherEffect.d.ts
  foundry/specialEffects/snowWeatherEffect.d.ts
  index.d.ts
  package-lock.json
  package.json
  types/augments/pixiParticles.d.ts
Labels: foundry 0.7.9, version update

#313 0.7.9/grids
  foundry/pixi/containers/baseGrid.d.ts
  foundry/pixi/containers/baseGrids/hexagonalGrid.d.ts
  foundry/pixi/containers/baseGrids/squareGrid.d.ts
  foundry/pixi/containers/canvasLayers/gridLayer.d.ts
  foundry/pixi/graphics/gridHighlight.d.ts
  index.d.ts
Labels: foundry 0.7.9, version update

#315 Update Ruler to 0.7.9
  foundry/pixi/containers/ruler.d.ts
Labels: foundry 0.7.9, version update

#528 Update infrastructure
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement, foundry 0.7.9

#529 Add a CODEOWNERS file
  CODEOWNERS
Labels: enhancement, foundry 0.7.9

#530 Add a CODEOWNERS file to master
  CODEOWNERS
Labels: enhancement
