Repository League-of-Foundry-Developers/foundry-vtt-types, pull requests merged in 2021-01, with the labels that each got.

#225 chore: update readme to reflect change in package location
  README.md
Labels: documentation

#231 Improve typing of actor properties in Item and ItemSheet
  types/applications/forms/item.d.ts
  types/framework/entities/item.d.ts
Labels: bug, foundry 0.7.9

#228 Update type declarations for prototypes.d.ts
  types/prototypes.d.ts
Labels: enhancement, foundry 0.7.9

#216 improve typing of ActiveEffects
  index.d.ts
  types/core/hooks.d.ts
  types/framework/entities/activeEffect.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/embeddedEntity.d.ts
  types/framework/entities/item.d.ts
Labels: foundry 0.7.9, version update

#4 [RDY] More Entity updates
  index.d.ts
  package-lock.json
  types/applications/forms/item.d.ts
  types/augments/utility-types.d.ts
  types/framework/collection.d.ts
  types/framework/entities/activeEffect.d.ts
  types/framework/entities/actor.d.ts
  types/framework/entities/chatMessage.d.ts
  types/framework/entities/combat.d.ts
  types/framework/entities/folder.d.ts
  types/framework/entities/item.d.ts
  types/framework/entities/journal.d.ts
  types/framework/entities/macro.d.ts
  types/framework/entities/playlist.d.ts
  types/framework/entities/rollTable.d.ts
  types/framework/entities/scene.d.ts
  types/framework/entities/user.d.ts
  types/framework/entity.d.ts
  types/framework/entityCollection.d.ts
  types/typesUtils.d.ts
Labels: foundry 0.7.9, version update

#235 Remove some eslint errors
  types/applications/baseEntitySheet.d.ts
  types/applications/forms/actor.d.ts
  types/applications/forms/item.d.ts
  types/framework/entities/actor.d.ts
Labels: enhancement, foundry 0.7.9, good first issue

#236 Make Actor.OwnedItemData more robust
  types/framework/entities/actor.d.ts
Labels: enhancement, foundry 0.7.9
